alias ga='git add'
alias gap='git add -p'
alias gs='git status'
alias gl='git pull'
alias gpu='git push'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gg='git grep'
alias gd='git diff'
alias gst='git diff main --compact-summary'
alias gca='git commit --amend'
alias glo='git log --pretty=reference'
alias gbr='git for-each-ref --sort=-committerdate refs/heads/ --format="%(committerdate:short) %(refname:short)"'
